### ISSUE TITLE
Add alternate outputs : TCP, UDP...

### ISSUE THREAD

**Issue by menardorama** [smartmarmot/DBforBIX#1]
Hi,

I'm using dbforbix for a long time now.

Due to the recent new time series technologies (influxdb, PrometeusDB, Elasticsearch...) we faced to the need to have dashboards.

We are using Grafana for that (it's amazing) and we use the Grafana Zabbix plugin.

But it's not enough, we need to have more than what is collected with zabbix.

For example : 
- List of all sessions with their context (lock, status, physical read/write....)
- Table statistics
  ....

Actually DBForbix is only focussed on zabbix but it could be much more.

In my previous company some Devs managed to add a simple TCP output in parallel of the zabbix output (it was with dbforbix 0.6).

But the ideal situation would be to have a per query routing mechanism (Zabbix or TCP or Both).

My Holly Graal would be to have an Oracle DBConsole for all supported DBs hosted in a time series database.

I hope I was interesting  :-)

Thanks

**Comment by menardorama** [comment]
Please find the work done on 0.6.1 version.

We added udp connector so that we are sure that Zabbix will not be impacted in case of fail alternate service response time.

[dbforbix-udp (1).zip](https://github.com/smartmarmot/DBforBIX/files/558249/dbforbix-udp.1.zip)

**Comment by smartmarmot** [comment]
Thank you for sharing! I've done time ago a version for graphite/carbon (when grafana was not yet developed ) anyway your is a good advice. Most likely is better have a separate fork.

**Comment by menardorama** [comment]
Well having a fork mean that you may run 2 dbforbix and consume more connections.

For Oracle it's not an issue but on postgresql ....

**Comment by menardorama** [comment]
My example was to be used with a logstash udp input.
