### ISSUE TITLE
 dbforbix-2.2-beta-ilnux64 oracle

### ISSUE THREAD

**Issue by askifyouneed** [smartmarmot/DBforBIX#15]
I can't see in the version 2.2 in the file META-INF/MANIFEST.MF the Class-Path to ojdbc driver like it was in the previous versions.
And there is no configuration for Oracle in the config.properties.sample also.

**Comment by smartmarmot** [comment]
Yes this is not an issue even DB2 is missing, the .sample contains examples of usage.

**Comment by askifyouneed** [comment]
But what about ojdbc driver, why it is missed?

**Comment by smartmarmot** [comment]
This choice is driven by the fact that I can't redistribute the Oracle JDBC driver as well as DB2 etc. that said I can't know which version of the library the admin is going to put in the lib directory. Then is better to use the global classpath (that in any case will override the one specified in the manifest.mf) this avoid the issue of use ojdbc6 vs other versions.
