### ISSUE TITLE
DB4bix

### ISSUE THREAD

**Issue by vagabondan** [smartmarmot/DBforBIX#17]
Hi, Andrea!
I've already tried to contact you through your site and wrote about some modifications in DBforBix code to integrate it with Zabbix Web interface because I have very strong demand on it.
I don't know your roadmap of DBforBix and many modifications were done in sources, that's why I've created new project.
But I think it's better to work in one direction on one project. What do you think?
[DB4bix link](https://github.com/vagabondan/db4bix/wiki)

**Comment by smartmarmot** [comment]
Hi Vagabondan! 
What you've done looks interesting, I think you've forked an old release and not the last one. Could you merge the last version of the code of mine a create a pull request? I don't think it make much sense have two different project.

**Comment by smartmarmot** [comment]
Checking your code in this way is definitely too difficult as you've not forked you've started a new project changing even the header of all the files so they appear all different. Why don't just fork the project on github and push your changes back once done? This is the way how github works.

**Comment by vagabondan** [comment]
Well, I needed fast results, almost had no time and had several questions to existing implementation. 
But it's not a big problem, I'll fork your project and reimplement changes made. Changing headers back is just a refactor in Eclipse.

**Comment by vagabondan** [comment]
Andrea, could you please explain what is the purpose of PersistenceDB and Persistent(Stack|DB)Sender? Are you trying to keep data while Zabbix Server is unavailable and send it later?

**Comment by smartmarmot** [comment]
Of course I can :) I wrote a persistence layer that initially was file based, and now is DB based. Practically if for some reason Zabbix server is not available the items instead of getting lost are saved to an application database (H2). Once the server is back available the items saved on the DB are retrieved and sent. Doing so you can restart freely the Zabbix server without losing data.

**Comment by smartmarmot** [comment]
Thank you for forking! doing so I can follow your changes.

**Comment by vagabondan** [comment]
Ok, thank you for explanation. 
It resembles almost the alternative java realization of vendor's Zabbix Proxy. After implementing the web interface integration it will be like an ordinary Zabbix Proxy.
But advanced DB queries require modifications of php web interface of Zabbix itself. Now users have to write XML to SQL query field of ordinary DB monitor agent type, that is not very handy. I believe, we need separate agent type for DBforBix proxy and several new standard predefined keys. I'm going to create corresponding request in Zabbix Jira for that.
As an alternative, it would be great to have an imbedded opportunity in Zabbix to customize it's interface, attaching external tools without php code modifications. But I still have no worthwhile idea how to do this with low blood.

**Comment by smartmarmot** [comment]
I am thinking that most likely the less impact approach would be:
1) Implement the zabbix active agent protocol
2) Use the query as active items
3) the DBforBIX need then to ask for the values and time shedules
Anyway it means redesign completely the scheduler included in dbforbix.
Also... it will not avoid to have the query written somewhere like in an active agent.

**Comment by vagabondan** [comment]
I've prepared modifications for DBforBix. Let's shift our discussion to pull request.
