### ISSUE TITLE
Service refuse to start

### ISSUE THREAD

**Issue by menardorama** [smartmarmot/DBforBIX#2]
Starting dbforbix.sh from shell fail to start, the error log look like this 

`
Switching umask back to 022 from 077
user changed to 'dbforbix'
Using default JVM in /usr/java/default/jre/lib/amd64/server/libjvm.so
Attemtping to load library /usr/java/default/jre/lib/amd64/server/libjvm.so
JVM library /usr/java/default/jre/lib/amd64/server/libjvm.so loaded
JVM library entry point found (0x803B4F10)
+-- DUMPING JAVA VM CREATION ARGUMENTS -----------------
| Version:                       0x010004
| Ignore Unrecognized Arguments: False
| Extra options:                 2
|   "-Xmx64m" (0x00000000)
|   "-Djava.class.path=/opt/dbforbix/dbforbix.jar:/opt/dbforbix/.:/opt/dbforbix/lib/commons-cli-1.3.1.jar:/opt/dbforbix/lib/httpcore-4.4.4.jar:/opt/dbforbix/lib/commons-codec-1.9.jar:/opt/dbforbix/lib/jtds-1.3.1.jar:/opt/dbforbix/lib/commons-collections-3.2.2.jar:/opt/dbforbix/lib/log4j-1.2.17.jar:/opt/dbforbix/lib/commons-configuration-1.10.jar:/opt/dbforbix/lib/logback-classic-1.0.13.jar:/opt/dbforbix/lib/commons-daemon-1.0.15.jar:/opt/dbforbix/lib/logback-core-1.0.13.jar:/opt/dbforbix/lib/commons-dbcp-1.4.jar:/opt/dbforbix/lib/mysql-connector-java-5.1.38.jar:/opt/dbforbix/lib/commons-lang-2.6.jar:/opt/dbforbix/lib/ojdbc6.jar:/opt/dbforbix/lib/commons-logging-1.2.jar:/opt/dbforbix/lib/postgresql-9.4.1207.jre7.jar:/opt/dbforbix/lib/commons-pool-1.6.jar:/opt/dbforbix/lib/slf4j-api-1.7.5.jar:/opt/dbforbix/lib/dom4j-1.6.1.jar:/opt/dbforbix/lib/xml-apis-1.0.b2.jar:/opt/dbforbix/lib/fastjson-1.2.8.jar:/opt/dbforbix/lib/zabbix-sender-0.0.1.jar:/opt/dbforbix/lib/httpclient-4.5.2.jar" (0x00000000)
+-------------------------------------------------------
| Internal options:              4
|   "-Dcommons.daemon.process.id=11888" (0x00000000)
|   "-Dcommons.daemon.process.parent=11887" (0x00000000)
|   "-Dcommons.daemon.version=1.0.13" (0x00000000)
|   "abort" (0x00405760)
+-------------------------------------------------------
Java VM created successfully
Class org/apache/commons/daemon/support/DaemonLoader found
Native methods registered
java_init done
Daemon loading...
java.lang.ClassNotFoundException: com.smartmarmot.dbforbix.DBforBIX
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:151)
Cannot load daemon
java_load failed
Service exit with a return value of 3
`

Also there is some libraries missing : 
1. httpcore-4.4.4.jar
2. zabbix-sender-0.0.1.jar
3. httpclient-4.5.2.jar
4. ojdbc.jar (I know that's normal)

I tried to add them (found on central.maven.org) but it still fail.

Any idea ?

My environment is Centos 7 Oracle JDK8 (also tried with openjdk same result) and Zabbix 3.04

**Comment by smartmarmot** [comment]
I'll review and check if I've missed some libs before commit.

**Comment by smartmarmot** [comment]
I've fixed the issue, I've updated the class in my project, now the dbforbix.sh is right.

**Comment by smartmarmot** [comment]
I've done a dryrun and it worked perfectly then I consider this issue closed, in case you still face problem let me know.
