### ISSUE TITLE
init not found in beta 2.2

### ISSUE THREAD

**Issue by tiago-cruz-movile** [smartmarmot/DBforBIX#23]
In documentation

http://www.smartmarmot.com/wiki/index.php?title=DBforBIX#Common_.28Universal.29_Installation_Steps

"Copy file /opt/dbforbix/init.d/dbforbix to /etc/init.d/dbforbix"

There is no "init.d" directory :) (but the systemd works!)

I think that you can leave both examples there :+1:

**Comment by smartmarmot** [comment]
I don't have any linux that still uses the init.d I'll change the wiki
