### ISSUE TITLE
Source of documentation is down.

### ISSUE THREAD

**Issue by P6rguVyrst** [smartmarmot/DBforBIX#28]
www.smartmarmot.com
This Account has been suspended.
Contact your hosting provider for more information.

**Comment by smartmarmot** [comment]
Thank you for the heads-up! I'm already opening an issue to my provider, this is actually very odd..

**Comment by darrynv** [comment]
It's back up now! Thanks!

**Comment by smartmarmot** [comment]
I'm glad you're happy to have the website back! I've actually solved the issue few hours later, the provider suspended the account because was under attack(not my website but the provider itself)
