### ISSUE TITLE
oracle tablespace usage

### ISSUE THREAD

**Issue by ZUNbado** [smartmarmot/DBforBIX#29]
Hi,

I have detected a problem with query to get a tablespace usage:

`SELECT tablespace_name,SUM(NVL(bytes,0)) AS bytes FROM dba_data_files GROUP BY tablespace_name`

This query returns number of bytes cached in a view, if this limit is reached at any moment and then decreased again, this view is not updated, then the check fails.

As a solution we purpose to update the query to some this one:

```
select rpad(ESPACIO.ts,18) as tablespace_name,
       lpad((ESPACIO.total - LIBRE.total),15) as bytes
from
       (select tablespace_name ts,sum(bytes) total from sys.dba_data_files
        group by tablespace_name) ESPACIO,
       (select tablespace_name ts,sum(bytes) total from sys.dba_free_space
        group by tablespace_name) LIBRE
```

Is this possible? 

Kind regards

**Comment by vagabondan** [comment]
Hi! Which template version do you mean?

**Comment by ZUNbado** [comment]
Hi, in current version for example (i have and older version, but is the same query)

https://raw.githubusercontent.com/smartmarmot/DBforBIX/master/zbx_templates/zbx_template_DB4bix.Oracle.Instances.xml

```
 <discovery_rule>
                    <name>Tablespaces</name>
                    .......
                    <key>oracle.discovery.DB4bix.config[tablespace,{$DSN}]</key>
                    .....
                    <params>&lt;parms type=&quot;oracle&quot; prefix=&quot;oracle.&quot;&gt;&#13;
	&lt;server&gt;&#13;
		&lt;discovery time=&quot;600&quot; item=&quot;discovery.DB4bix.config[tablespace,{$DSN}]&quot; names=&quot;TABLESPACE&quot;&gt;SELECT DISTINCT name FROM v$tablespace WHERE name NOT IN ('TEMP')&lt;/discovery&gt;&#13;
		&lt;multiquery time=&quot;300&quot; items=&quot;tablespace.bytes[%1]|tablespace.maxbytes[%1]&quot; type=&quot;column&quot;&gt;SELECT tablespace_name,SUM(NVL(bytes,0)) AS bytes, SUM(maxbytes) AS maxbytes FROM dba_data_files GROUP BY tablespace_name&lt;/multiquery&gt;&#13;
	&lt;/server&gt;&#13;
&lt;/parms&gt;</params>
....
```

**Comment by ZUNbado** [comment]
Hi @vagabondan any new on this? Thanks

**Comment by henriquehaag** [comment]
Hi guys! Check this out:
- Total bytes:
SELECT a.tablespace tablespace_name,trunc(a.total,2) AS bytes
FROM (SELECT d.TABLESPACE_NAME tablespace,SUM(d.bytes) Total
FROM dba_data_files d GROUP BY d.TABLESPACE_NAME) a order by 1;
- Total usage:
SELECT a.tablespace tablespace_name,trunc(a.used,2) "BYTES"
FROM (SELECT d.TABLESPACE_NAME tablespace,(SUM(d.bytes)-(SELECT SUM(bytes)
FROM dba_free_space WHERE tablespace_name=d.TABLESPACE_NAME)) Used
FROM dba_data_files d GROUP BY d.TABLESPACE_NAME) a;
