### ISSUE TITLE
Zabbix templates are not compatible with 3.0

### ISSUE THREAD

**Issue by menardorama** [smartmarmot/DBforBIX#3]
Hi
The zabbix templates (at least the postgresql one) are not compatible with the latest zabbix version.

I upload you the corrected version for postgresql
[zbx_postgresql_xml.txt](https://github.com/smartmarmot/DBforBIX/files/558327/zbx_postgresql_xml.txt)

**Comment by smartmarmot** [comment]
Unfortunately I know... the new template set is not compatible with this new version, as well as the configuration files. This is due the refactoring, the usage of xml for items instead of properties files. I've stated this on my website, but the comment is right!
