### ISSUE TITLE
Notes for 2.4 installation

### ISSUE THREAD

**Issue by KJlt77** [smartmarmot/DBforBIX#38]
Just installed successfully 2.4 on Ubuntu (14.04.5 LTS) and I have some notes witch may be helpful to others.

1. DBforBIX 2.4 runs only on JRE8. I have faced error on 7, although there is required min 7 in Wiki.

2. I’ve wasted some time figuring out why DBforBIX do not read configuration from Zabbix server. The problem was case sensitivity in proxy name: In config.properties – DBforBIX, in Wiki – DBforBix. I know I have to be more observant when configuring system, but even small things may save some our valuable time :) Could you fix this in Wiki for the other people? :)

3. Small typo: when logging, version is referenced as 2.4-beta, as everywhere else as 2.4.

4. I hope, someday you’ll merge and improve missing documentation from smartmarmot.com wiki. By the way, IMHO, it’s not a good idea to grant SELECT ANY TABLE on Oracle to monitoring user. SELECT ANY DICTIONARY is more than enough for typical configuration.

Thanks for a nice tool, waiting for next releases :)

**Comment by vagabondan** [comment]
@KJlt77 thank you very much for your attention and comments!

1. Java 8, you are right, my fault. There are some lambda functions inside as I remember.
2. These names should absolutely coincide in Zabbix Server and dbforbix config file
3. Thanks, we'll check it.
4. Could you please provide the reference in DBforBIX documentation where SELECT ANY TABLE is stated to be required?

**Comment by KJlt77** [comment]
4. I'm talking about old wiki: http://www.smartmarmot.com/wiki/index.php?title=DBforBIX

> Install steps for Oracle
> Create a User (ZABBIX) for DBforBIX to access your Oracle Database. You can use the following script:
> 
>   CREATE USER ZABBIX
>   IDENTIFIED BY <REPLACE WITH PASSWORD>
>   DEFAULT TABLESPACE SYSTEM
>   TEMPORARY TABLESPACE TEMP
>   PROFILE DEFAULT
>   ACCOUNT UNLOCK;
>   -– 2 Roles for ZABBIX
>   GRANT CONNECT TO ZABBIX;
>   GRANT RESOURCE TO ZABBIX;
>   ALTER USER ZABBIX DEFAULT ROLE ALL;
>   –- 5 System Privileges for ZABBIX
>   **GRANT SELECT ANY TABLE TO ZABBIX;**
>   GRANT CREATE SESSION TO ZABBIX;	
>   GRANT SELECT ANY DICTIONARY TO ZABBIX;
>   GRANT UNLIMITED TABLESPACE TO ZABBIX;
>  GRANT SELECT ANY DICTIONARY TO ZABBIX;

It is not stated as required, but may be considered as recommended :)

**Comment by smartmarmot** [comment]
@KJlt77 Thank you very much for all your comments!
Actually I knew about the JDK8 but I didn't noticed the issue: good spot!
Well about the wiki I'll fix it

**Comment by smartmarmot** [comment]
I've fixed the wiki, thank you for your notes!
