### ISSUE TITLE
MSSQL monitoring

### ISSUE THREAD

**Issue by KJlt77** [smartmarmot/DBforBIX#41]
Hi,

Had some fun trying to monitor MSSQL using DBforBIX. Here are my findings :)

1. DBforBIX tries to use jTDS driver (same as for Sybase) which is not packed in dbforbix_run.jar. Putting jtds-1.3.1.jar in CLASSPATH environment variable doesn't work, it must be inside dbforbix_run.jar.

2. jTDS latest version doesn't work with SQL Server 2014 and 2016. Solution is to use Microsoft's JDBC driver.

Steps:
2.1. Download driver from https://www.microsoft.com/en-in/download/details.aspx?id=11774

2.2. Replace class name in src/com/smartmarmot/dbforbix/db/DBConstants.java variable MSSQL_DRIVER with "com.microsoft.sqlserver.jdbc.SQLServerDriver".

2.3. Rebuild DBforBIX.

2.4. Pack compiled classes, external jars and MS driver (sqljdbc_6.0/enu/jre8/sqljdbc42.jar) into dbforbix_run.jar. Don't forget to mention new jar in manifest file if packing manually.

2.5. Replace old dbforbix_run.jar with new and restart service.

Worked for me.

Is it possible to include this stuff in future versions? Thanks.

**Comment by smartmarmot** [comment]
Thank you for this detailed guide. This is something that can definitely be done. The only concern I have is tied with the license of the Microsoft driver. I am not sure that can be redistributed freely. I will definitely check. Thank you!

**Comment by smartmarmot** [comment]
I've built the new version 3.0 that include your suggestion. Thank you!
