### ISSUE TITLE
Something wrong with build scripts?

### ISSUE THREAD

**Issue by KJlt77** [smartmarmot/DBforBIX#44]
Is it some reason to have two similar jars?

dist/dbforbix_run.jar
dist/dbforbix_run_3.0-beta.jar

dbforbix_run.jar (build 5 hours ago) contains outdated files and dist/dbforbix_run_3.0-beta.jar (build 3 days ago) looks ok.

MSSQL driver sqljdbc42.jar is not included in neither.

![image](https://user-images.githubusercontent.com/23154801/30926930-6e66ce4c-a3bf-11e7-8f6e-5849a7941c8b.png)

**Comment by smartmarmot** [comment]
I just approved a pull request that's why there is still a bit of confusion.
About the MSSQL driver I can't redistribute them because of the Microsoft policy, so I can't include them on my package.

**Comment by KJlt77** [comment]
Redistribution policy is in licence.txt file in the driver's package. Section 2.a "Distributable Code" describes distributions conditions. I didn't see any contradictions there.

**Comment by smartmarmot** [comment]
Distribution Restrictions. You may not
* alter any copyright, trademark or patent notice in the Distributable Code;

The DBforBIX is released under GPLv3 then if I am not wrong if I redistribute the microsoft drivers in a GPLv3 package I'm changing the license. 
The same is for the Oracle drivers... I think I'll change the documentation following your suggestion but I am not sure if include the  proprietary drivers.

**Comment by KJlt77** [comment]
I'm not too much familiar with licenses types, but if you can't distribute proprietary drivers, shouldn't they be committed in this repository in any folder or jar? Because now I can see them in some places and in some not. Good documentation about how to download and link JDBC to DBforBIX for users by itself would be very useful. I think outdated documentation now is the big issue for this project. But anyway thanks for the good job and quick responce.

**Comment by smartmarmot** [comment]
Thank you for your suggestion I'll see what I can do within those days.
