### ISSUE TITLE
Shippable

### ISSUE THREAD

**Issue by vagabondan** [smartmarmot/DBforBIX#46]
Andrea, could you please share "shippable.yml" if you get one?
Last merges reads that you've enabled shippable CI, haven't you?

**Comment by smartmarmot** [comment]
Unfortunately the shippable wasn't working properly so I removed the configuration but it looks still enabled.

**Comment by smartmarmot** [comment]
it should be removed now...

**Comment by smartmarmot** [comment]
I've added you as a collaborator. You can now commit directly :)

**Comment by vagabondan** [comment]
Ok, thanks:)
