### ISSUE TITLE
Lost documentation.

### ISSUE THREAD

**Issue by bigsow** [smartmarmot/DBforBIX#5]
I know that it is the beta version, but could you add some clue how to install and use it.
From the documentation (I think that a little bit obsolete) I know how to install it on RHEL server but:
1. Is it necessary to start the service as root?
2. What for is the jsvc and how to use it?
3. Which environment variables is necessary to start it from systemd (JAVA_HOME etc)
4. What for is the network ACL for Oracle database user, to resolve what... hostnames?
5. There is no lines about specification of queries in config.properties.sample. I know that the queries are now in the items/oracle.xml file, so how to put them to the config file.
6. And finally the main question, how it works. How the data are pushed to the Zabbix (via trap, so should I confiure something)

**Comment by smartmarmot** [comment]
Hello here are the responses:
 1. No there is no need to use root 
 2. JSVC is an Apache.org framework used to "easily" (somehow easily:) ) demonize java software
 3. all the environment are set with the startup script dbforbix.sh you find in the .zip package
 4. the Oracle account creation is explained here: [http://www.smartmarmot.com/wiki/index.php?title=DBforBIX#Install_steps_for_Oracle](http://www.smartmarmot.com/wiki/index.php?title=DBforBIX#Install_steps_for_Oracle)
 5. the query item file is defined for each database in the main properties file config.properties (you have to fill the config.properties.sample file and rename it as config.properties)
 6. DBforBIX is sending Zabbix Item to a Zabbix Trapper so on the server side you need to configure as Zabbix Trapper (BTW there are some templates included in the distribution)

You can find the documentation on my website: [www.smartmarmot.com](www.smartmarmot.com) under the section wiki or simply here: [http://www.smartmarmot.com/wiki/index.php?title=DBforBIX#Installation](http://www.smartmarmot.com/wiki/index.php?title=DBforBIX#Installation)
NOTE: The documentation is not complete I'm still working on it.

**Comment by bigsow** [comment]
5. In your config properties.sample file is not any one line about queries, so I do not know how to configure.
There is only database section like:
`DB.DB2.Type`
Shoud I use something like that:
`DB.DB2.QueryListFile=`
Should I use:
`DatabaseList=DB2`
?
Where should I put information about Query file which is in path items/oracle.xml?

**Comment by bigsow** [comment]
Is it possible to publish a full example of config.properties?

**Comment by smartmarmot** [comment]
Right, here is an example for Oracle

DB.DB2.Type=oracle
DB.DB2.Name=OraSRV
DB.DB2.Url=jdbc:oracle:thin:@192.168.100.100:1521/ORCL
DB.DB2.User=ZABBIX
DB.DB2.Password=ZABBIX_PWD
DB.DB2.MaxWait=10
DB.DB2.MaxSize=10
DB.DB2.MaxIdle=1
DB.DB2.ItemFile=oracle

Each database needs to be defined by a group . The $DATABASE in the following parameters should be replaced by a server name or number.

DB.$DATABASE.Type
The database type of this entry.
Possible values: pgsql, oracle, mssql, mysql
Default: none

DB.$DATABASE.Name
The name of the database in your zabbix screens. This value must match this name or no values will be visible.
Possible values: a possible zabbix host name
Default: none

DB.$DATABASE.Instance
An optional instance parameter. This parameter is used to replace %INSTANCE% parameters in item queries.
Possible values: a possible identifier
Default: none

DB.$DATABASE.Url
The JDBC url of the database connection.
Possible values: a valid JDBC URL
Default: none

DB.$DATABASE.User
A user which is allowed to send the defined item queries to the database.
Possible values: a valid user name
Default: none

You also see that you can define some jdbc pool specific items:
DB.DB2.MaxWait=10
DB.DB2.MaxSize=10
DB.DB2.MaxIdle=1
and finally the itemfile to use
DB.DB2.ItemFile=oracle

I definitely need to sort out the documentation

DB.$DATABASE.Password
The password of the user.
Possible values: a valid password of the user
Default: none

**Comment by bigsow** [comment]
So DB.DB2.ItemFile=oracle means - to take the oracle.xml file from the item folder right, and run all queries from it?
And which parameter is bind with the Zabbix Host Name?
When I create the new Zabbix Host Name and pin "Template App Oracle Instance" which field do I have to fill in: Agent Interfaces, SNMP Interfaces, JMX Interfaces or IPMI Interfaces?

**Comment by smartmarmot** [comment]
Exaclty, the zabbix Host Name must be OraSRV
e.g. as per our file:
DB.DB2.Name=OraSRV

**Comment by smartmarmot** [comment]
btw now I'm focused to implement the persistence of the items on filesystem, so if your zabbix server is down for maintenance you're not losing your items, this will be a interesting feature.

**Comment by bigsow** [comment]
Could you answer about the second part of my question:
"...which field do I have to fill in: Agent Interfaces, SNMP Interfaces, JMX Interfaces or IPMI Interfaces?.."
So I am curious which type of host must be or it does not matter?

**Comment by smartmarmot** [comment]
Hi The item must be of the kind "Zabbix trapper" anyway you can use the template included in the distribution, importing those templates you have an example of how it works.

**Comment by bigsow** [comment]
I did not ask about item type but about host type? Ok I will try the "Agent Interfaces" type.
