### ISSUE TITLE
It does not support Zabbix 4

### ISSUE THREAD

**Issue by wanghy8166** [smartmarmot/DBforBIX#62]
When will it be repaired? The reasons are as follows:

https://www.zabbix.com/documentation/4.0/manual/installation/upgrade_notes_400#plain_text_protocol_dropped

Plain text protocol dropped
Support for the plain text protocol has been dropped and a header is now mandatory. A header has been added to Zabbix get requests, Zabbix server/proxy passive check requests and frontend requests to Zabbix server.

As a consequence, Zabbix agents that are older than version 1.4 are no longer supported. Also, messages from self-written senders will be rejected if the header is absent. Whereas previously Zabbix trappers would accept messages without headers as well as messages with headers, now they will only accept messages with protocol header.

**Comment by wanghy8166** [comment]
Orabbix has the same problem.

**Comment by rtau** [comment]
For reference, zabbix 4.0 manual provide examples on how to generate the header required in various languages.
https://www.zabbix.com/documentation/4.0/manual/appendix/protocols/header_datalen

**Comment by wanghy8166** [comment]
> For reference, zabbix 4.0 manual provide examples on how to generate the header required in various languages.
> https://www.zabbix.com/documentation/4.0/manual/appendix/protocols/header_datalen

Yes, I started learning Eclipse and compiled and exported new jar file, as follows:
https://github.com/wanghy8166/dbforbix06/blob/master/dbforbix-0.6.1.jar
https://github.com/wanghy8166/orabbix/blob/master/orabbix-1.2.4.jar

**Comment by rtau** [comment]
If it works for you, maybe you could create a pull request for so others could benefit as well?

**Comment by isoinh** [comment]
@wanghy8166, did you manage to get it working?

We are using dbforbix-2.2-beta and can't get it to work. We've tried to add:
`byte[] header = new byte[] {`
`    'Z', 'B', 'X', 'D', '\1',`
`    (byte)(data.length & 0xFF),`
`    (byte)((data.length >> 8) & 0xFF),`
`    (byte)((data.length >> 16) & 0xFF),`
`    (byte)((data.length >> 24) & 0xFF),`
`    '\0', '\0', '\0', '\0'};`
to ZabbixSender.java file after line 116 (`LOG.warn("ZabbixSender - messageWithoutHeader:" + dataAsString);` without success.

@smartmarmot, do you perhaps have any insight for this problem?

**Comment by juu7nitw23** [comment]
we are very interested in a solution as well

**Comment by lucassebben** [comment]
@wanghy8166  Thanks for the .jar file.
I'm using this and almost all queries are sending data to Zabbix server correctly but few are showing connection error with server.
I'm running Orabbix on the Zabbix server (version 4.0.2) and the log return "Message from 127.0.0.1 is shorter than expected 12435439 bytes. Message ignored.". I've checked the timestamp and match with Hit Ratio and Pin Hit Ratio queries.

@smartmarmot Do you have plans to implement the header on version Orabbix 1.2.3? That was running smoothly!

**Comment by wanghy8166** [comment]
> @wanghy8166 Thanks for the .jar file.
> I'm using this and almost all queries are sending data to Zabbix server correctly but few are showing connection error with server.
> I'm running Orabbix on the Zabbix server (version 4.0.2) and the log return "Message from 127.0.0.1 is shorter than expected 12435439 bytes. Message ignored.". I've checked the timestamp and match with Hit Ratio and Pin Hit Ratio queries.
> 
> @smartmarmot Do you have plans to implement the header on version Orabbix 1.2.3? That was running smoothly!

Please refer to:
https://github.com/wanghy8166/orabbix/blob/master/Add%20support%20for%20Zabbix%204.txt

**Comment by smartmarmot** [comment]
Unfortunately no plan so far as I moved on a different role years ago and I don't have anymore chance to test it. (e.g. no DB and no Zabbix where I'm currently working :) )

**Comment by roemdo** [comment]
This was working for me

`						


		String dataAsString = protocol.encodeItem(nextItem);
							
		byte[] data = dataAsString.getBytes("UTF-8");
		
		byte[] header = new byte[] {
			 'Z', 'B', 'X', 'D', '\1',
			(byte)(data.length & 0xFF),
			(byte)((data.length >> 8) & 0xFF),
			(byte)((data.length >> 16) & 0xFF),
			(byte)((data.length >> 24) & 0xFF),
			'\0', '\0', '\0', '\0'};
							 
			byte[] packet = new byte[header.length + data.length];
			System.arraycopy(header, 0, packet, 0, header.length);
			System.arraycopy(data, 0, packet, header.length, data.length);
						
			os.write(packet);
			os.flush();

			in = zabbix.getInputStream();
			final int read = in.read(response);
				
			if (!protocol.isResponeOK(read, response))
			LOG.warn("ZabbixSender - received unexpected response (class ZabbixSender)'" + new String(response).trim() + "' for key '" + nextItem.getKey()
						+ "'");
			break;
}`

**Comment by ultramanyuan** [comment]
looks like not support "dbxxx.ExtraQueryListFile" in configuration file anymore .Appreciate for any help about that.

**Comment by wanghy8166** [comment]
> looks like not support "dbxxx.ExtraQueryListFile" in configuration file anymore .Appreciate for any help about that.

Please try the orabbix-1.2.4w.jar file

**Comment by ricardorava** [comment]
I'm using Orabbix v1.2.3 and with the help of my coleague Bernardo found a solution. We changed just the file Sender.class in orabbix-1.2.3.jar. We used Eclipse to edit and save.

1 - Download orabbix-src-1.2.3.zip from https://sourceforge.net/projects/orabbix/files/

2 - Edit Sender.java file located at ./com.smartmarmot/orabbix/

2.1 - Original Code
...
Socket zabbix = null;
        OutputStreamWriter out = null;
        InputStream in = null;
        Enumeration<String> serverlist  = zabbixServers.keys();

        while (serverlist.hasMoreElements()){
        	String zabbixServer = serverlist.nextElement();
	        try {
				zabbix = new Socket(zabbixServer, zabbixServers.get(
						zabbixServer).intValue());
	            zabbix.setSoTimeout(TIMEOUT);
	
	            out = new OutputStreamWriter(zabbix.getOutputStream());
	            out.write(message.toString());
	            out.flush();
				...
2.2 - New code
...
        Socket zabbix = null;
//        OutputStreamWriter out = null;
        OutputStream out = null;
        InputStream in = null;
        Enumeration<String> serverlist  = zabbixServers.keys();

        while (serverlist.hasMoreElements()){
        	String zabbixServer = serverlist.nextElement();
	        try {
				zabbix = new Socket(zabbixServer, zabbixServers.get(
						zabbixServer).intValue());
	            zabbix.setSoTimeout(TIMEOUT);

    	    byte[] data = message.toString().getBytes("UTF-8");

    	    byte[] header = new byte[] {
	        'Z', 'B', 'X', 'D', '\1',
			(byte)(data.length & 0xFF),
			(byte)((data.length >> 8) & 0xFF),
			(byte)((data.length >> 16) & 0xFF),
			(byte)((data.length >> 24) & 0xFF),
			'\0', '\0', '\0', '\0'};
						 
		    byte[] packet = new byte[header.length + data.length];
		    System.arraycopy(header, 0, packet, 0, header.length);
		    System.arraycopy(data, 0, packet, header.length, data.length);
	
//	            out = new OutputStreamWriter(zabbix.getOutputStream());
	            out = zabbix.getOutputStream();
	            out.write(packet);
	            out.flush();
				...

3 - Compile Sender.java generating the file Sender.class

NOTE: You will need the files located at ./lib (orabbix-1.2.3.zip)

4 - In the original file orabbix-1.2.3.jar substitute just the file Sender.class, located at ./com/smartmarmot/orabbix/

NOTE: Don't compile all project

5 - Restart Orabbix

**Comment by ErwinUZA** [comment]
Has this been resolved for DBforBIX? 
We use this for monitoring MSSQL, Oracle and Sybase databases.

**Comment by smartmarmot** [comment]
Hmmm sorry guys but I am not able to replicate the issue with Version 2.4-beta.
You're using a quite old version of orabbix (really old actually).

**Comment by smartmarmot** [comment]
Can you please let me know how exactly you're experiencing this issue? I'm trying with zabbix 4.0.2 and it works perfectly.

**Comment by smartmarmot** [comment]
Ahhhh I realized all of you are referring to the old Orabbix!

**Comment by smartmarmot** [comment]
I'm now closing this issue as it refers to another product.

**Comment by StepFH** [comment]
Has anyone encountered such a problem? Please help solve this problem.
I add code like this ：
   
    byte[] data = message.toString().getBytes("UTF-8");
    byte[] header = new byte[] {
	        'Z', 'B', 'X', 'D', '\1',
			(byte)(data.length & 0xFF),
			(byte)((data.length >> 8) & 0xFF),
			(byte)((data.length >> 16) & 0xFF),
			(byte)((data.length >> 24) & 0xFF),
			'\0', '\0', '\0', '\0'};
						 
    byte[] packet = new byte[header.length + data.length];
    System.arraycopy(header, 0, packet, 0, header.length);
    System.arraycopy(data, 0, packet, header.length, data.length);

But when the code was executed at 
   `zabbix = new Socket(zabbixServer, ((Integer)this.zabbixServers.get(zabbixServer)).intValue());`
An exception has occurred：
     `
java.net.SocketTimeoutException: Read timed out
 2019-02-14 14:42:53,986 [pool-1-thread-3] ERROR Orabbix - Error contacting Zabbix server 10.10.9.47  on port 10051
`
but if I try to connect client to server with ‘ping’ or 'telnet' command , it success.
I don't know why the connection timed out.By the way I used 30000ms as timeout's time.

**Comment by oapinis85** [comment]
> I'm using Orabbix v1.2.3 and with the help of my coleague Bernardo found a solution. We changed just the file Sender.class in orabbix-1.2.3.jar. We used Eclipse to edit and save.
> 1 - Download orabbix-src-1.2.3.zip from https://sourceforge.net/projects/orabbix/files/
> 2 - Edit Sender.java file located at ./com.smartmarmot/orabbix/
> 2.1 - Original Code
>         Socket zabbix = null;
>         OutputStreamWriter out = null;
>         InputStream in = null;
>         Enumeration<String> serverlist  = zabbixServers.keys();
> 
>         while (serverlist.hasMoreElements()){
>         	String zabbixServer = serverlist.nextElement();
> 	        try {
> 				zabbix = new Socket(zabbixServer, zabbixServers.get(
> 						zabbixServer).intValue());
> 	            zabbix.setSoTimeout(TIMEOUT);
> 	
> 	            out = new OutputStreamWriter(zabbix.getOutputStream());
> 	            out.write(message.toString());
> 	            out.flush();
> 
> 
> 2.2 - New code
>         Socket zabbix = null;
> //      OutputStreamWriter out = null;
>         OutputStream out = null;
>         InputStream in = null;
>         Enumeration<String> serverlist  = zabbixServers.keys();
> 
>         while (serverlist.hasMoreElements()){
>         	String zabbixServer = serverlist.nextElement();
> 	        try {
> 				zabbix = new Socket(zabbixServer, zabbixServers.get(
> 						zabbixServer).intValue());
> 	            zabbix.setSoTimeout(TIMEOUT);
> 
>     	    byte[] data = message.toString().getBytes("UTF-8");
> 
>     	    byte[] header = new byte[] {
> 	        'Z', 'B', 'X', 'D', '\1',
> 			(byte)(data.length & 0xFF),
> 			(byte)((data.length >> 8) & 0xFF),
> 			(byte)((data.length >> 16) & 0xFF),
> 			(byte)((data.length >> 24) & 0xFF),
> 			'\0', '\0', '\0', '\0'};
> 						 
> 		    byte[] packet = new byte[header.length + data.length];
> 		    System.arraycopy(header, 0, packet, 0, header.length);
> 		    System.arraycopy(data, 0, packet, header.length, data.length);
> 	
> //	            out = new OutputStreamWriter(zabbix.getOutputStream());
> 	            out = zabbix.getOutputStream();
> 	            out.write(packet);
> 	            out.flush();
> 
> 3 - Compile Sender.java generating the file Sender.class
> NOTE: You will need the files located at ./lib (orabbix-1.2.3.zip)
> 4 - In the original file orabbix-1.2.3.jar substitute just the file Sender.class, located at ./com/smartmarmot/orabbix/
> NOTE: Don't compile all project
> 5 - Restart Orabbix

Hello!

We did it what you decribet, but did not work for as, 
We also have orabbix version 1.2.3
How you compiled the file? 
We compiled:
"
export PATH=~/tmp/jdk1.8.0_202/bin:$PATH
export SOURCEPATH=~/tmp
export CLASSPATH=~/tmp/lib/*

javac -classpath "$CLASSPATH" -sourcepath "$SOURCEPATH" com/smartmarmot/orabbix/Sender.java
Compilde file: ~/tmp/com/smartmarmot/orabbix/Sender.class
"

**Comment by ricardorava** [comment]
> > I'm using Orabbix v1.2.3 and with the help of my coleague Bernardo found a solution. We changed just the file Sender.class in orabbix-1.2.3.jar. We used Eclipse to edit and save.
> > 1 - Download orabbix-src-1.2.3.zip from https://sourceforge.net/projects/orabbix/files/
> > 2 - Edit Sender.java file located at ./com.smartmarmot/orabbix/
> > 2.1 - Original Code
> > Socket zabbix = null;
> > OutputStreamWriter out = null;
> > InputStream in = null;
> > Enumeration serverlist  = zabbixServers.keys();
> > ```
> >     while (serverlist.hasMoreElements()){
> >     	String zabbixServer = serverlist.nextElement();
> >       try {
> >   		zabbix = new Socket(zabbixServer, zabbixServers.get(
> >   				zabbixServer).intValue());
> >           zabbix.setSoTimeout(TIMEOUT);
> > 
> >           out = new OutputStreamWriter(zabbix.getOutputStream());
> >           out.write(message.toString());
> >           out.flush();
> > ```
> > 2.2 - New code
> > Socket zabbix = null;
> > //      OutputStreamWriter out = null;
> > OutputStream out = null;
> > InputStream in = null;
> > Enumeration serverlist  = zabbixServers.keys();
> > ```
> >     while (serverlist.hasMoreElements()){
> >     	String zabbixServer = serverlist.nextElement();
> >       try {
> >   		zabbix = new Socket(zabbixServer, zabbixServers.get(
> >   				zabbixServer).intValue());
> >           zabbix.setSoTimeout(TIMEOUT);
> > 
> > 	    byte[] data = message.toString().getBytes("UTF-8");
> > 
> > 	    byte[] header = new byte[] {
> >       'Z', 'B', 'X', 'D', '\1',
> >   	(byte)(data.length & 0xFF),
> >   	(byte)((data.length >> 8) & 0xFF),
> >   	(byte)((data.length >> 16) & 0xFF),
> >   	(byte)((data.length >> 24) & 0xFF),
> >   	'\0', '\0', '\0', '\0'};
> >   				 
> >       byte[] packet = new byte[header.length + data.length];
> >       System.arraycopy(header, 0, packet, 0, header.length);
> >       System.arraycopy(data, 0, packet, header.length, data.length);
> > ```
> > //	            out = new OutputStreamWriter(zabbix.getOutputStream());
> > out = zabbix.getOutputStream();
> > out.write(packet);
> > out.flush();
> > 3 - Compile Sender.java generating the file Sender.class
> > NOTE: You will need the files located at ./lib (orabbix-1.2.3.zip)
> > 4 - In the original file orabbix-1.2.3.jar substitute just the file Sender.class, located at ./com/smartmarmot/orabbix/
> > NOTE: Don't compile all project
> > 5 - Restart Orabbix
> 
> Hello!
> 
> We did it what you decribet, but did not work for as,
> We also have orabbix version 1.2.3
> How you compiled the file?
> We compiled:
> "
> export PATH=/tmp/jdk1.8.0_202/bin:$PATH
> export SOURCEPATH=/tmp
> export CLASSPATH=~/tmp/lib/*
> 
> javac -classpath "$CLASSPATH" -sourcepath "$SOURCEPATH" com/smartmarmot/orabbix/Sender.java
> Compilde file: ~/tmp/com/smartmarmot/orabbix/Sender.class
> "

Hi, we used Eclipse to edit and compile.  Don't forget that you will need the files located at ./lib (orabbix-1.2.3.zip) to compile Sender.java.

**Comment by AldoriJunior** [comment]
Hi,

Someone fixed the header in DBforBIX ? I can send data to Zabbix 3, but in Zabbix 4, the ZabbixSender[resp] come NULL.

[2019-04-16 20:37:50] [DEBUG] [127.0.0.1:10052/DBforBIX/ZABBIX/ZABBIX/mysql.test.DBforBix.config[teste,ZABBIX][run(Scheduler.java:87)]]: Scheduler.run() 30
[2019-04-16 20:37:50] [DEBUG] [ZabbixSender[run(ZabbixSender.java:99)]]: ZabbixSender: Sending to 127.0.0.1:10052 Items[1]=[ZABBIX mysql.test.DBforBix.config[teste,ZABBIX]: 91]
[2019-04-16 20:37:50] [DEBUG] [ZabbixSender[run(ZabbixSender.java:123)]]: ZabbixSender[data]: {"request":"history data","host":"DBforBIX","data":[{"host":"ZABBIX","key":"mysql.test.DBforBix.config[teste,ZABBIX]","value":"91","clock":1555447070,"ns":0}],"clock":"1555447070","ns":"0"}
[2019-04-16 20:37:50] [DEBUG] [ZabbixSender[run(ZabbixSender.java:125)]]: ZabbixSender[resp]:

**Comment by linwinfan** [comment]
I have pull code and change code ,build and test on zabbix4.2.
please go to :  https://github.com/linwinfan/dbforbix4.2

**Comment by smartmarmot** [comment]
There is no pull request on this repo.

**Comment by nitro67** [comment]
> I have pull code and change code ,build and test on zabbix4.2.
> please go to : https://github.com/linwinfan/dbforbix4.2

hello, I used your version dbforbix4.2, but i have the same error..
[2019-12-16 16:32:42] [ERROR] [main[requestZabbix(Config.java:832)]]: Zabbix Server (152.139.69.40:10051) has returned empty response for request:
{"request":"proxy config","host":"DBforBIX"}
[2019-12-16 16:32:42] [ERROR] [main[getZabbixConfigurationItems(Config.java:922)]]: Error parsing json objects from Zabbix Server (152.139.69.40:10051): null
[2019-12-16 16:32:42] [ERROR] [main[getZabbixConfigurationItems(Config.java:1048)]]: Error getting item Zabbix Config from Zabbix Server (152.139.69.40:10051): null


any suggestion ??? What can i did wrong ??

**Comment by smartmarmot** [comment]
> > I have pull code and change code ,build and test on zabbix4.2.
> > please go to : https://github.com/linwinfan/dbforbix4.2
> 
> hello, I used your version dbforbix4.2, but i have the same error..
> [2019-12-16 16:32:42] [ERROR] [main[requestZabbix(Config.java:832)]]: Zabbix Server (152.139.69.40:10051) has returned empty response for request:
> {"request":"proxy config","host":"DBforBIX"}
> [2019-12-16 16:32:42] [ERROR] [main[getZabbixConfigurationItems(Config.java:922)]]: Error parsing json objects from Zabbix Server (152.139.69.40:10051): null
> [2019-12-16 16:32:42] [ERROR] [main[getZabbixConfigurationItems(Config.java:1048)]]: Error getting item Zabbix Config from Zabbix Server (152.139.69.40:10051): null
> 
> any suggestion ??? What can i did wrong ??

please create a pull I'll approve

**Comment by vagabondan** [comment]
Hello everyone!
You can try this one db4bix version rewritten in Nodejs:
https://github.com/vagabondan/node-db4bix
