### ISSUE TITLE
 	dbforbix-2.0-beta-linux64.zip to git

### ISSUE THREAD

**Issue by askifyouneed** [smartmarmot/DBforBIX#7]
Is it possible to put unzipped dbforbix to git where users will be able to commit changes in templates and database queries

**Comment by smartmarmot** [comment]
Yes I like the idea, but I prefer keep the distribution done as archive but what I can do is pubblished the item directory, the template is already present there on git and is the one that I use to build the distribution.

**Comment by askifyouneed** [comment]
Ok great. now I have got some graph and trigger prototypes against tablespaces. Thank you for your work.

**Comment by askifyouneed** [comment]
Could you also add systemd directory to repository?

**Comment by smartmarmot** [comment]
yes sure is not an issue, do you have something to commit there?

**Comment by smartmarmot** [comment]
done you can find it under dists/linux/systemd

**Comment by askifyouneed** [comment]
Yes, I made a systemd unit file to start the jar directly without using JSVC. It could be an alternative. So mabye I call it differently.

**Comment by smartmarmot** [comment]
well doing so you can't stop it in an elegant manner I think... but anyway let me see I'm curious.

**Comment by askifyouneed** [comment]
Let's see. And one remark when you prepare bash scripts, please to put Unix format of ending line like LF not CRLF, which you have in dbforbix.sh and dbforbix.service files.

**Comment by smartmarmot** [comment]
the files are in unix format I don't have any ^m shown in my vim

**Comment by askifyouneed** [comment]
I saw this in your dist/dbforbix-2.0-beta-linux64.zip. Now I'm checking and in the new files is ok :), but no wait, still int the dbforbix-2.1-beta-linux64.tar.gz/systemd/dbforbix.service CRLF exists

**Comment by smartmarmot** [comment]
ops! :) thanks!
